#!/bin/bash

# MISP Kubernetes Deployment Script
# This script provides an easy way to deploy MISP on Kubernetes

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
NAMESPACE="misp"
RELEASE_NAME="misp"
HELM_CHART_PATH="./helm-charts/misp"
VALUES_FILE=""
DRY_RUN=false
UPGRADE=false

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Function to show usage
show_usage() {
    cat << EOF
MISP Kubernetes Deployment Script

Usage: $0 [OPTIONS]

Options:
    -n, --namespace NAME     Kubernetes namespace (default: misp)
    -r, --release NAME      Helm release name (default: misp)
    -f, --values FILE       Custom values file
    -d, --dry-run          Dry run mode (don't actually deploy)
    -u, --upgrade          Upgrade existing deployment
    -h, --help             Show this help message

Examples:
    # Deploy MISP with default settings
    $0

    # Deploy with custom values file
    $0 -f custom-values.yaml

    # Deploy in specific namespace
    $0 -n security -r misp-prod

    # Dry run to see what would be deployed
    $0 -d

    # Upgrade existing deployment
    $0 -u

EOF
}

# Function to check prerequisites
check_prerequisites() {
    print_status "Checking prerequisites..."

    # Check if kubectl is installed
    if ! command -v kubectl &> /dev/null; then
        print_error "kubectl is not installed. Please install kubectl first."
        exit 1
    fi

    # Check if helm is installed
    if ! command -v helm &> /dev/null; then
        print_error "Helm is not installed. Please install Helm first."
        exit 1
    fi

    # Check if kubectl can connect to cluster
    if ! kubectl cluster-info &> /dev/null; then
        print_error "Cannot connect to Kubernetes cluster. Please check your kubeconfig."
        exit 1
    fi

    print_success "Prerequisites check passed"
}

# Function to create namespace
create_namespace() {
    print_status "Creating namespace: $NAMESPACE"
    
    if ! kubectl get namespace $NAMESPACE &> /dev/null; then
        kubectl create namespace $NAMESPACE
        print_success "Namespace $NAMESPACE created"
    else
        print_warning "Namespace $NAMESPACE already exists"
    fi
}

# Function to validate Helm chart
validate_helm_chart() {
    print_status "Validating Helm chart..."
    
    if [ ! -d "$HELM_CHART_PATH" ]; then
        print_error "Helm chart not found at $HELM_CHART_PATH"
        exit 1
    fi
    
    if ! helm lint "$HELM_CHART_PATH"; then
        print_error "Helm chart validation failed"
        exit 1
    fi
    
    print_success "Helm chart validation passed"
}

# Function to generate default values
generate_default_values() {
    if [ -z "$VALUES_FILE" ]; then
        VALUES_FILE="/tmp/misp-default-values.yaml"
        cat > "$VALUES_FILE" << EOF
# MISP Default Values
# Generated by deployment script

# Database configuration
database:
  mysql:
    auth:
      rootPassword: "$(openssl rand -base64 32)"
      password: "$(openssl rand -base64 32)"

# MISP configuration
misp:
  env:
    MISP_BASEURL: "https://misp.local"
    MISP_ORG: "MISP Organization"
    MISP_EMAIL: "admin@misp.local"

# Ingress configuration (disabled by default)
misp:
  ingress:
    enabled: false

# Resource limits
misp:
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

workers:
  replicaCount: 2
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
EOF
        print_warning "Using generated default values. Consider creating a custom values file for production."
    fi
}

# Function to deploy MISP
deploy_misp() {
    print_status "Deploying MISP..."
    
    local helm_cmd="helm"
    local helm_args=""
    
    if [ "$DRY_RUN" = true ]; then
        helm_args="$helm_args --dry-run"
        print_warning "Running in dry-run mode"
    fi
    
    if [ "$UPGRADE" = true ]; then
        helm_cmd="$helm_cmd upgrade"
        print_status "Upgrading existing deployment"
    else
        helm_cmd="$helm_cmd install"
        print_status "Installing new deployment"
    fi
    
    $helm_cmd $RELEASE_NAME "$HELM_CHART_PATH" \
        --namespace "$NAMESPACE" \
        --values "$VALUES_FILE" \
        --wait \
        --timeout 10m \
        $helm_args
    
    if [ "$DRY_RUN" = false ]; then
        print_success "MISP deployment completed"
    fi
}

# Function to show deployment status
show_status() {
    if [ "$DRY_RUN" = true ]; then
        return
    fi
    
    print_status "Checking deployment status..."
    
    echo
    echo "=== Pod Status ==="
    kubectl get pods -n "$NAMESPACE" -l app.kubernetes.io/name=misp
    
    echo
    echo "=== Services ==="
    kubectl get services -n "$NAMESPACE" -l app.kubernetes.io/name=misp
    
    echo
    echo "=== Persistent Volume Claims ==="
    kubectl get pvc -n "$NAMESPACE"
    
    echo
    echo "=== Access Information ==="
    echo "To access MISP, run:"
    echo "  kubectl port-forward -n $NAMESPACE svc/$RELEASE_NAME-app 8080:80"
    echo "Then visit: http://localhost:8080"
    
    echo
    echo "=== Logs ==="
    echo "To view logs, run:"
    echo "  kubectl logs -n $NAMESPACE -f deployment/$RELEASE_NAME-app"
    echo "  kubectl logs -n $NAMESPACE -f deployment/$RELEASE_NAME-mysql"
    echo "  kubectl logs -n $NAMESPACE -f deployment/$RELEASE_NAME-redis"
}

# Function to cleanup
cleanup() {
    if [ -f "$VALUES_FILE" ] && [ "$VALUES_FILE" != "" ] && [ "$VALUES_FILE" != "/tmp/misp-default-values.yaml" ]; then
        rm -f "$VALUES_FILE"
    fi
}

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -n|--namespace)
            NAMESPACE="$2"
            shift 2
            ;;
        -r|--release)
            RELEASE_NAME="$2"
            shift 2
            ;;
        -f|--values)
            VALUES_FILE="$2"
            shift 2
            ;;
        -d|--dry-run)
            DRY_RUN=true
            shift
            ;;
        -u|--upgrade)
            UPGRADE=true
            shift
            ;;
        -h|--help)
            show_usage
            exit 0
            ;;
        *)
            print_error "Unknown option: $1"
            show_usage
            exit 1
            ;;
    esac
done

# Set trap for cleanup
trap cleanup EXIT

# Main execution
main() {
    echo "=== MISP Kubernetes Deployment Script ==="
    echo
    
    check_prerequisites
    create_namespace
    validate_helm_chart
    generate_default_values
    deploy_misp
    show_status
    
    print_success "Deployment script completed successfully!"
}

# Run main function
main
