{{- if .Values.database.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "misp.fullname" . }}-mysql
  labels:
    {{- include "misp.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  mysql-root-password: {{ .Values.database.mysql.auth.rootPassword | b64enc | quote }}
  mysql-password: {{ .Values.database.mysql.auth.password | b64enc | quote }}
{{- end }}

{{- if .Values.redis.enabled }}
{{- if .Values.redis.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "misp.fullname" . }}-redis
  labels:
    {{- include "misp.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
type: Opaque
data:
  redis-password: {{ .Values.redis.auth.password | b64enc | quote }}
{{- end }}
{{- end }}

{{- if .Values.secrets.create }}
{{- if .Values.secrets.gpgKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "misp.fullname" . }}-gpg
  labels:
    {{- include "misp.labels" . | nindent 4 }}
type: Opaque
data:
  gpg.key: {{ .Values.secrets.gpgKey | quote }}
{{- end }}

{{- if or .Values.secrets.smimeCert .Values.secrets.smimeKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "misp.fullname" . }}-smime
  labels:
    {{- include "misp.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.smimeCert }}
  smime.crt: {{ .Values.secrets.smimeCert | quote }}
  {{- end }}
  {{- if .Values.secrets.smimeKey }}
  smime.key: {{ .Values.secrets.smimeKey | quote }}
  {{- end }}
{{- end }}
{{- end }}
