<?php
/**
 * Galaxy clusters import modal.
 *
 */
?>

<?= $this->element('genericElementsBS5/Forms/modal_header', [
    'accent' => 'galaxy',
    'eyebrow' => __('Galaxies'),
    'title' => __('Import galaxy clusters'),
    'titleIcon' => 'fas fa-upload',
    'icon' => 'misp-icon misp-icon-galaxy misp-simple',
]) ?>

<!-- ── BODY ─────────────────────────────────────────────────── -->
<div class="p-4">

    <div class="alert alert-warning d-flex gap-2" role="alert">
        <i class="fas fa-triangle-exclamation mt-1"></i>
        <div>
            <?= __('Use galaxy files generated by a MISP instance. Do <u>not</u> try to import a galaxy from the MISP-galaxy file format / GitHub repository, as this will fail.') ?>
            <div class="small mt-1">
                <?= __('For more information on adding galaxies see the') ?>
                <a href="https://www.circl.lu/doc/misp/galaxy/#adding-a-new-galaxy" target="_blank" rel="noopener">
                    <?= __('MISP-book') ?>
                </a>.
            </div>
        </div>
    </div>

    <?php
    echo $this->Form->create('Galaxy', [
        'url' => $baseurl . '/galaxies/import',
        'id' => 'galaxyImportForm',
        'enctype' => 'multipart/form-data',
    ]);
    ?>

    <!-- JSON -->
    <div class="mb-3">
        <?= $this->element('genericElementsBS5/Forms/json_field', [
            'field' => 'json',
            'accent' => 'galaxy',
            'label' => __('Galaxy Clusters JSON'),
            'id' => 'GalaxyJson',
            'rows' => 14,
            'minHeight' => '280px',
            'placeholder' => "{\n    \"Galaxy\": {\n        \"name\": \"…\"\n    },\n    \"GalaxyCluster\": []\n}",
            'hint' => __('An export of this or another MISP instance — leave it empty to upload the file instead.'),
        ]) ?>
    </div>

    <!-- JSON FILE -->
    <div class="mb-4">
        <label class="form-label fw-semibold" for="GalaxySubmittedjson"><?= __('JSON file') ?></label>
        <?= $this->Form->file('submittedjson', [
            'class' => 'form-control bg-light',
            'id' => 'GalaxySubmittedjson',
        ]) ?>
        <div class="form-text">
            <?= __('Optionally upload a .json file instead of pasting its content above.') ?>
        </div>
    </div>

    <!-- ACTIONS -->
    <div class="d-flex justify-content-end gap-3">
        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">
            <?= __('Cancel') ?>
        </button>
        <button type="submit" class="btn btn-galaxy text-light">
            <i class="fas fa-upload me-1"></i> <?= __('Import') ?>
        </button>
    </div>

    <?= $this->Form->end(); ?>

</div>
