-- Generated from the real fetchAttributes condition/ACL builder and MysqlExtended.
-- Synthetic exact-10-acl case, 100000 attribute fixture, MariaDB 10.11.19.
-- PRIMARY KEY(id), standard indexes. SQL is identical with the legacy deleted index.

-- Existing OR
SELECT Attribute.*, Event.id, Event.info, Event.org_id, Event.orgc_id, Event.uuid, Event.user_id, Event.threat_level_id, Event.distribution, Event.analysis, Event.date, Event.timestamp, Object.id, Object.distribution, Object.sharing_group_id, Object.timestamp, CASE WHEN Attribute.value2 = '' THEN Attribute.value1 ELSE CONCAT(Attribute.value1, '|', Attribute.value2) END AS Attribute__value FROM `attributes` AS `Attribute`  JOIN `misp_restsearch_test`.`events` AS `Event` ON (`Event`.`id` = `Attribute`.`event_id`) LEFT JOIN `misp_restsearch_test`.`objects` AS `Object` ON (`Object`.`id` = `Attribute`.`object_id`)  WHERE ((`Attribute`.`deleted` = 0) AND (((`Event`.`org_id` = 1) OR (((((((`Event`.`distribution` IN (1, 2, 3))  AND  (`Event`.`published` = 1))) OR (((`Event`.`distribution` = 4)  AND  (`Event`.`sharing_group_id` = (1))  AND  (`Event`.`published` = 1))))) AND (((`Attribute`.`distribution` IN (1, 2, 3, 5)) OR (((`Attribute`.`distribution` = 4) AND (`Attribute`.`sharing_group_id` = (1)))))) AND (((`Attribute`.`object_id` = 0) OR (`Object`.`distribution` IN (1, 2, 3, 5)) OR (((`Object`.`distribution` = 4) AND (`Object`.`sharing_group_id` = (1)))))))))) AND (((`Attribute`.`value1` IN ('missing-32323.example', 'ioc-038398.example', 'missing-48523.example', 'ioc-032221.example', 'missing-55226.example', 'ioc-064697.example', 'missing-26702.example', 'ioc-003571.example', 'missing-84313.example', 'ioc-004301.example')) OR (`Attribute`.`value2` IN ('missing-32323.example', 'ioc-038398.example', 'missing-48523.example', 'ioc-032221.example', 'missing-55226.example', 'ioc-064697.example', 'missing-26702.example', 'ioc-003571.example', 'missing-84313.example', 'ioc-004301.example')))))   ORDER BY `Attribute`.`id` ASC  LIMIT 500;

-- Candidate ID UNION (deduplicating)
SELECT Attribute.*, Event.id, Event.info, Event.org_id, Event.orgc_id, Event.uuid, Event.user_id, Event.threat_level_id, Event.distribution, Event.analysis, Event.date, Event.timestamp, Object.id, Object.distribution, Object.sharing_group_id, Object.timestamp, CASE WHEN Attribute.value2 = '' THEN Attribute.value1 ELSE CONCAT(Attribute.value1, '|', Attribute.value2) END AS Attribute__value FROM `attributes` AS `Attribute`  JOIN `misp_restsearch_test`.`events` AS `Event` ON (`Event`.`id` = `Attribute`.`event_id`) LEFT JOIN `misp_restsearch_test`.`objects` AS `Object` ON (`Object`.`id` = `Attribute`.`object_id`) INNER JOIN (SELECT id FROM attributes WHERE value1 IN ('missing-32323.example', 'ioc-038398.example', 'missing-48523.example', 'ioc-032221.example', 'missing-55226.example', 'ioc-064697.example', 'missing-26702.example', 'ioc-003571.example', 'missing-84313.example', 'ioc-004301.example') UNION SELECT id FROM attributes WHERE value2 IN ('missing-32323.example', 'ioc-038398.example', 'missing-48523.example', 'ioc-032221.example', 'missing-55226.example', 'ioc-064697.example', 'missing-26702.example', 'ioc-003571.example', 'missing-84313.example', 'ioc-004301.example')) AS `ValueMatch` ON (`ValueMatch`.`id` = `Attribute`.`id`)  WHERE ((`Attribute`.`deleted` = 0) AND (((`Event`.`org_id` = 1) OR (((((((`Event`.`distribution` IN (1, 2, 3))  AND  (`Event`.`published` = 1))) OR (((`Event`.`distribution` = 4)  AND  (`Event`.`sharing_group_id` = (1))  AND  (`Event`.`published` = 1))))) AND (((`Attribute`.`distribution` IN (1, 2, 3, 5)) OR (((`Attribute`.`distribution` = 4) AND (`Attribute`.`sharing_group_id` = (1)))))) AND (((`Attribute`.`object_id` = 0) OR (`Object`.`distribution` IN (1, 2, 3, 5)) OR (((`Object`.`distribution` = 4) AND (`Object`.`sharing_group_id` = (1)))))))))))   ORDER BY `Attribute`.`id` ASC  LIMIT 500;
