<?php

declare(strict_types=1);

use Phinx\Seed\AbstractSeed;

class RolesSeeder extends AbstractSeed
{
    public function run(): void
    {
        $data = [
            [
                'id' => 1,
                'name' => 'admin',
                'created' => date('Y-m-d H:i:s'),
                'modified' => date('Y-m-d H:i:s'),
                'perm_add' => 1,
                'perm_modify' => 1,
                'perm_modify_org' => 1,
                'perm_publish' => 1,
                'perm_publish_zmq' => 1,
                'perm_publish_kafka' => 1,
                'perm_sync' => 1,
                'perm_admin' => 1,
                'perm_audit' => 1,
                'perm_full' => 1,
                'perm_auth' => 1,
                'perm_regexp_access' => 1,
                'perm_tagger' => 1,
                'perm_site_admin' => 1,
                'perm_template' => 1,
                'perm_sharing_group' => 1,
                'perm_tag_editor' => 1,
                'perm_delegate' => 1,
                'perm_sighting' => 1,
                'perm_object_template' => 1,
                'perm_decaying' => 1,
                'default_role' => 1,
                'memory_limit' => NULL,
                'max_execution_time' => NULL,
                'restricted_to_site_admin' => 0,
                'enforce_rate_limit' => 0,
                'rate_limit_count' => 0,
                'perm_galaxy_editor' => 1,
                'perm_warninglist' => 1,
                'perm_view_feed_correlations' => 1,
                'perm_analyst_data' => 1,
                'perm_skip_otp' => 0
            ],
            [
                'id' => 2,
                'name' => 'Org Admin',
                'created' => date('Y-m-d H:i:s'),
                'modified' => date('Y-m-d H:i:s'),
                'perm_add' => 1,
                'perm_modify' => 1,
                'perm_modify_org' => 1,
                'perm_publish' => 1,
                'perm_publish_zmq' => 1,
                'perm_publish_kafka' => 1,
                'perm_sync' => 0,
                'perm_admin' => 1,
                'perm_audit' => 1,
                'perm_full' => 0,
                'perm_auth' => 1,
                'perm_regexp_access' => 0,
                'perm_tagger' => 1,
                'perm_site_admin' => 0,
                'perm_template' => 1,
                'perm_sharing_group' => 1,
                'perm_tag_editor' => 1,
                'perm_delegate' => 1,
                'perm_sighting' => 1,
                'perm_object_template' => 0,
                'perm_decaying' => 1,
                'default_role' => 0,
                'memory_limit' => NULL,
                'max_execution_time' => NULL,
                'restricted_to_site_admin' => 0,
                'enforce_rate_limit' => 0,
                'rate_limit_count' => 0,
                'perm_galaxy_editor' => 1,
                'perm_warninglist' => 0,
                'perm_view_feed_correlations' => 0,
                'perm_analyst_data' => 1,
                'perm_skip_otp' => 0
            ],
            [
                'id' => 3,
                'name' => 'User',
                'created' => date('Y-m-d H:i:s'),
                'modified' => date('Y-m-d H:i:s'),
                'perm_add' => 1,
                'perm_modify' => 1,
                'perm_modify_org' => 1,
                'perm_publish' => 0,
                'perm_publish_zmq' => 0,
                'perm_publish_kafka' => 0,
                'perm_sync' => 0,
                'perm_admin' => 0,
                'perm_audit' => 1,
                'perm_full' => 0,
                'perm_auth' => 1,
                'perm_regexp_access' => 0,
                'perm_tagger' => 1,
                'perm_site_admin' => 0,
                'perm_template' => 0,
                'perm_sharing_group' => 0,
                'perm_tag_editor' => 0,
                'perm_delegate' => 0,
                'perm_sighting' => 0,
                'perm_object_template' => 1,
                'perm_decaying' => 0,
                'default_role' => 1,
                'memory_limit' => NULL,
                'max_execution_time' => NULL,
                'restricted_to_site_admin' => 0,
                'enforce_rate_limit' => 0,
                'rate_limit_count' => 0,
                'perm_galaxy_editor' => 1,
                'perm_warninglist' => 0,
                'perm_view_feed_correlations' => 0,
                'perm_analyst_data' => 1,
                'perm_skip_otp' => 0
            ],
            [
                'id' => 4,
                'name' => 'Publisher',
                'created' => date('Y-m-d H:i:s'),
                'modified' => date('Y-m-d H:i:s'),
                'perm_add' => 1,
                'perm_modify' => 1,
                'perm_modify_org' => 1,
                'perm_publish' => 1,
                'perm_publish_zmq' => 1,
                'perm_publish_kafka' => 1,
                'perm_sync' => 0,
                'perm_admin' => 0,
                'perm_audit' => 1,
                'perm_full' => 0,
                'perm_auth' => 1,
                'perm_regexp_access' => 0,
                'perm_tagger' => 1,
                'perm_site_admin' => 0,
                'perm_template' => 0,
                'perm_sharing_group' => 0,
                'perm_tag_editor' => 0,
                'perm_delegate' => 0,
                'perm_sighting' => 1,
                'perm_object_template' => 1,
                'perm_decaying' => 0,
                'default_role' => 1,
                'memory_limit' => NULL,
                'max_execution_time' => NULL,
                'restricted_to_site_admin' => 0,
                'enforce_rate_limit' => 0,
                'rate_limit_count' => 0,
                'perm_galaxy_editor' => 1,
                'perm_warninglist' => 0,
                'perm_view_feed_correlations' => 0,
                'perm_analyst_data' => 1,
                'perm_skip_otp' => 0
            ],
            [
                'id' => 5,
                'name' => 'Sync user',
                'created' => date('Y-m-d H:i:s'),
                'modified' => date('Y-m-d H:i:s'),
                'perm_add' => 1,
                'perm_modify' => 1,
                'perm_modify_org' => 1,
                'perm_publish' => 1,
                'perm_publish_zmq' => 1,
                'perm_publish_kafka' => 1,
                'perm_sync' => 1,
                'perm_admin' => 0,
                'perm_audit' => 1,
                'perm_full' => 0,
                'perm_auth' => 1,
                'perm_regexp_access' => 0,
                'perm_tagger' => 1,
                'perm_site_admin' => 0,
                'perm_template' => 0,
                'perm_sharing_group' => 1,
                'perm_tag_editor' => 1,
                'perm_delegate' => 1,
                'perm_sighting' => 1,
                'perm_object_template' => 1,
                'perm_decaying' => 0,
                'default_role' => 1,
                'memory_limit' => NULL,
                'max_execution_time' => NULL,
                'restricted_to_site_admin' => 0,
                'enforce_rate_limit' => 0,
                'rate_limit_count' => 0,
                'perm_galaxy_editor' => 1,
                'perm_warninglist' => 0,
                'perm_view_feed_correlations' => 0,
                'perm_analyst_data' => 1,
                'perm_skip_otp' => 0
            ],
            [
                'id' => 6,
                'name' => 'Read Only',
                'created' => date('Y-m-d H:i:s'),
                'modified' => date('Y-m-d H:i:s'),
                'perm_add' => 0,
                'perm_modify' => 0,
                'perm_modify_org' => 0,
                'perm_publish' => 0,
                'perm_publish_zmq' => 0,
                'perm_publish_kafka' => 0,
                'perm_sync' => 0,
                'perm_admin' => 0,
                'perm_audit' => 1,
                'perm_full' => 0,
                'perm_auth' => 1,
                'perm_regexp_access' => 0,
                'perm_tagger' => 0,
                'perm_site_admin' => 0,
                'perm_template' => 0,
                'perm_sharing_group' => 0,
                'perm_tag_editor' => 0,
                'perm_delegate' => 0,
                'perm_sighting' => 0,
                'perm_object_template' => 0,
                'perm_decaying' => 0,
                'default_role' => 0,
                'memory_limit' => NULL,
                'max_execution_time' => NULL,
                'restricted_to_site_admin' => 0,
                'enforce_rate_limit' => 0,
                'rate_limit_count' => 0,
                'perm_galaxy_editor' => 0,
                'perm_warninglist' => 0,
                'perm_view_feed_correlations' => 0,
                'perm_analyst_data' => 0,
                'perm_skip_otp' => 0
            ]
        ];

        $roles = $this->table('roles');
        $roles->insert($data)
            ->saveData();
    }
}
